### ISSUE TITLE
ProDBG panics if plugin type is removed

### ISSUE THREAD

**Issue by emoon** [emoon/ProDBG#266]
When reloading a layout and a plugin-type is missing/can't be loaded it will panic:

```
thread '<main>' panicked at 'Could not restore view', src/prodbg/main/src/windows.rs:929

* thread #1: tid = 0x65962d, 0x00000001000203b9 prodbg`prodbg::windows::Window::load_layout::habfb5a3d74ee12b6 + 1865 at windows.rs:931, name = 'bgfx - renderer backend thread', queue = 'com.apple.main-thread', stop reason = breakpoint 1.1
  * frame #0: 0x00000001000203b9 prodbg`prodbg::windows::Window::load_layout::habfb5a3d74ee12b6 + 1865 at windows.rs:931
    frame #1: 0x000000010001ad16 prodbg`prodbg::windows::Windows::load::h8142219e00512f5b + 86 at windows.rs:227
    frame #2: 0x0000000100002473 prodbg`prodbg::main::ha2c16a4ca7fce97b + 2243 at main.rs:56
    frame #3: 0x00000001005bfe7e prodbg`std::panicking::try::call::hbbf4746cba890ca7 + 30
    frame #4: 0x00000001005c322c prodbg`__rust_try + 12
    frame #5: 0x00000001005c31c6 prodbg`__rust_maybe_catch_panic + 38
    frame #6: 0x00000001005bfca2 prodbg`std::rt::lang_start::hbcefdc316c2fbd45 + 562
    frame #7: 0x000000010001b2ea prodbg`main + 42 at duration.rs:80
    frame #8: 0x00007fff8ebc35ad libdyld.dylib`start + 1
```

This is a vaild case that may happen (say that user has removed the plugin) ProDBG shouldn't crash and should just ignore loading the plugin and don't create the dock where it was located.

**Comment by SlNPacifist** [comment]
Isn't it better to show error message instead? If user did not remove plugin (say, updated it to new version but it is broken for some reason), user at least can save his layout.

**Comment by emoon** [comment]
Yeah that is true. It should show a error message that it couldn't load plugin x and may have some options "Quit" or "Go on and skip the plugin" in that case it should be removed from the layout and ProDBG should go on as usually.
